FROM golang:1.25.1-alpine AS test

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV YUGABYTE_TEST_URL="postgres://yugabyte@yugabyte:5433/yugabyte?sslmode=disable"

CMD ["go", "test", "-v", "./storage/yugabyte", "./object", "./orm", "./schema"]