FROM golang:1.25.1-alpine AS test

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV SQLSERVER_TEST_URL="sqlserver://ddao:ddao_Password123@sqlserver:1433?database=ddao_test"

CMD ["go", "test", "-v", "./storage/sqlserver", "./object", "./orm", "./schema"]