version: '3.8'

services:
  # SQL Server service
  sqlserver:
    build:
      context: ./docker/sqlserver
      dockerfile: Dockerfile
    container_name: ddao-sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd123
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ddao-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd123 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 80s

  # Oracle service
  oracle:
    build:
      context: ./docker/oracle
      dockerfile: Dockerfile
    container_name: ddao-oracle
    hostname: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=OraclePassword123
      - ORACLE_DATABASE=DDAO
      - APP_USER=ddao_user
      - APP_USER_PASSWORD=ddao_password
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - ddao-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/OraclePassword123@localhost:1521/xe"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  # PostgreSQL service (for comparison and existing tests)
  postgres:
    image: postgres:15-alpine
    container_name: ddao-postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ddao_test
      - POSTGRES_USER=ddao_user
      - POSTGRES_PASSWORD=ddao_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ddao-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ddao_user -d ddao_test"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # MySQL/TiDB compatible service
  mysql:
    image: mysql:8.0
    container_name: ddao-mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ddao_test
      - MYSQL_USER=ddao_user
      - MYSQL_PASSWORD=ddao_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ddao-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # DDAO Test Runner service
  ddao-test:
    build:
      context: .
      dockerfile: docker/scripts/test.Dockerfile
    container_name: ddao-test-runner
    depends_on:
      sqlserver:
        condition: service_healthy
      oracle:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      # SQL Server connection
      - SQLSERVER_TEST_URL=sqlserver://sa:YourStrong@Passw0rd123@sqlserver:1433?database=ddao_test
      # Oracle connection
      - ORACLE_TEST_URL=oracle://ddao_user:ddao_password@oracle:1521/xe
      # PostgreSQL connection
      - POSTGRES_TEST_URL=postgres://ddao_user:ddao_password@postgres:5432/ddao_test?sslmode=disable
      # MySQL connection
      - MYSQL_TEST_URL=ddao_user:ddao_password@tcp(mysql:3306)/ddao_test
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - ddao-network
    profiles:
      - test
    command: ["go", "test", "./...", "-v"]

volumes:
  sqlserver_data:
    driver: local
  oracle_data:
    driver: local
  postgres_data:
    driver: local
  mysql_data:
    driver: local

networks:
  ddao-network:
    driver: bridge