version: '3.8'

services:
  ddao-test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CGO_ENABLED=1
    command: go test -v ./...

  ddao-dev:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CGO_ENABLED=1
    ports:
      - "8080:8080"
    command: go run .

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ddao_test
      POSTGRES_USER: ddao
      POSTGRES_PASSWORD: ddao_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ddao_test
      MYSQL_USER: ddao
      MYSQL_PASSWORD: ddao_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data: