FROM golang:1.25.1-alpine AS test

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV ORACLE_TEST_URL="oracle://ddao:ddao_password@oracle:1521/XE"

CMD ["go", "test", "-v", "./storage/oracle", "./object", "./orm", "./schema"]