FROM golang:1.25.1-alpine AS test

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV TIDB_TEST_URL="ddao:ddao_password@tcp(mysql:3306)/ddao_test"

CMD ["go", "test", "-v", "./storage/tidb", "./object", "./orm", "./schema"]