FROM golang:1.25.1-alpine AS test

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV COCKROACH_TEST_URL="postgres://root@cockroach:26257/defaultdb?sslmode=disable"

CMD ["go", "test", "-v", "./storage/cockroach", "./object", "./orm", "./schema"]