version: '3.8'

services:
  ddao-cockroach:
    build:
      context: .
      dockerfile: Dockerfile.cockroach
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CGO_ENABLED=1
      - COCKROACH_TEST_URL=postgres://root@cockroach:26257/defaultdb?sslmode=disable
    depends_on:
      - cockroach
    networks:
      - ddao-cockroach-network

  cockroach:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    networks:
      - ddao-cockroach-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cockroach_data:

networks:
  ddao-cockroach-network: